Fix bugs, add improvements

diff --git a/getrun b/getrun
--- a/getrun
+++ b/getrun
@@ -2,13 +2,26 @@
 
 usage()
 {
-    echo -e "Usage: $(basename "$0") <nd>
-        <nd> Required. Hostname or IP-address of ND
-        (-u|--username) <username>. Optional. Will use name from ssh config, if not specified
-        (-d|--device-os) [ios,nxos,junos,routeros,eltex]. Optional. Default: ios
-        (-c|--config-type) [running,startup], only for IOS/NXOS, Optional. Default: running
-        (-o|--output-file) Output file. Optional. Will autogenerate name, if not specified"
+    echo -e "Usage: $(basename "$0") [options] <nd>
+        Positional:
+        <nd> Required. Hostname or IP-address of Network Dievice
+        Options:
+        (-u|--username) <username>. Username. Optional, will use name from ssh config, if not specified
+        (-d|--device-os) Device OS [ios,nxos,junos,routeros,eltex]. Optional, default: ios
+        (-c|--config-type) Config type [running,startup], only for IOS/NXOS, Optional, default: running
+        (-o|--output-file) Output file. Optional, will autogenerate name, if not specified"
         1>&2
+}
+
+cleanup()
+{
+    if [ -f "$1" ]; then
+        if [ ! -s "$1" ]; then
+            rm "$1"
+        else
+            echo "Config saved to ${OUTPUT_FILE}."
+        fi
+    fi
 }
 
 OPTIONS=u:d:c:o:
@@ -70,13 +83,14 @@ fi
 [ "$OUTPUT_FILE" ] || OUTPUT_FILE=${DEVICE}_$(date +%Y-%m-%d_%H-%M-%S).conf
 [ "$USERNAME" ] && USERNAME="${USERNAME}@" || USERNAME=""
 
-# Remove empty output file if Ctrl-C pressed during password request
-trap '[ -f "${OUTPUT_FILE}" ] && [ ! -s "${OUTPUT_FILE}" ] && rm "${OUTPUT_FILE}"' SIGINT
+# Cleanup on Exit and break (Ctrl-C)
+trap "cleanup ${OUTPUT_FILE}" SIGINT
+trap "cleanup ${OUTPUT_FILE}" EXIT
 
 # Save configuration in output file
 case "$DEVICE_OS" in
     ios)
-        scp -q ${USERNAME}${DEVICE}:${CONFIG_TYPE}-config ${OUTPUT_FILE} #2>/dev/null
+        scp -q ${USERNAME}${DEVICE}:${CONFIG_TYPE}-config ${OUTPUT_FILE}
         ;;
     nxos)
         ssh ${USERNAME}${DEVICE} "show ${CONFIG_TYPE}-config | no-more" >${OUTPUT_FILE}
@@ -91,10 +105,8 @@ case "$DEVICE_OS" in
         ssh ${USERNAME}${DEVICE} "show running-config" >${OUTPUT_FILE}
         ;;
     *)
-        echo 'Unknown device OS!' >&2
+        echo "Unknown device OS!" >&2
         usage
         exit 1
         ;;
 esac
-
-echo "Config saved in ${OUTPUT_FILE}."
